### ISSUE TITLE
disable github pages

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/mccole#8]
I've tried disabling GitHub Pages on this site but it never sticks: every commit produces a "build failed" message in my inbox because there isn't a `docs` directory with HTML. cc @juananpe

**Comment by juananpe** [comment]
As a regular collaborator of the mccole repo, I can't see the settings page . What do you have there? https://github.com/juananpe/mccole/settings/pages
And in the Actions page?
https://github.com/juananpe/mccole/settings/actions
(I would try to disable Actions in this repo if we are not using them)

**Comment by gvwilson** [comment]
Turns out the way to disable it is to select `None` as the branch to publish from.
